"""empty message

Revision ID: 046a97401220
Revises: 6e64680fde9d
Create Date: 2017-10-25 13:17:39.664182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046a97401220'
down_revision = '6e64680fde9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('x_position', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('y_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'y_position')
    op.drop_column('users', 'x_position')
    # ### end Alembic commands ###
